### ISSUE TITLE
How To Work This

### ISSUE THREAD

**Issue by ptowns188** [mad-ady/ffserver-trigger#1]
Any chance you could help me get this running?

I understand the install process but not sure where to actually put the ffmpeg commands so the script knows which to start.

Thanks

**Comment by mad-ady** [comment]
You will need to define the stream inside ffserver configuration. I've added a link to an article I wrote on how to get it working to the Readme (https://magazine.odroid.com/wp-content/uploads/ODROID-Magazine-201610.pdf#page=12). Have a look and if you are still stuck let me know.
